import Head from "next/head";
import { useEffect, useState } from "react";
import { BoxPublic, Header, Loader } from "@/components";
import { Content, SideBar, NotPublics } from "@/styles/styles";
import { CompanyInfos } from "@/blocks";
import { IPublication } from "@/components/BoxPublic/BoxPublic";
import { usePosts } from "@/services";
import { useRouter } from "next/router";

export default function Empresa() {
  const router = useRouter();
  const { id } = router.query;
  const { posts, loading, mutate } = usePosts();
  const [postagensFiltradas, setPostagensFiltradas] = useState([]);

  useEffect(() => {
    if (!posts || !id) return;

    setPostagensFiltradas(
      posts.filter((postagem: any) => postagem.empresaId == id)
    );
  }, [posts, id]);

  return (
    <>
      <Head>
        <title>Munera Business</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/munera-logo.png" />
      </Head>
      <Loader isActive={loading} />
      <Header />
      <SideBar left>
        <CompanyInfos />
      </SideBar>
      <Content>
        {postagensFiltradas.length > 0 ? (
          postagensFiltradas?.map((publication: IPublication, key) => (
            <BoxPublic
              key={key}
              empresaName={publication.empresaName}
              icon={`${process.env.NEXT_PUBLIC_S3}/logos/${publication.empresaId}-logo.png`}
              date_time={publication.date_time}
              legenda={publication.legenda}
              midia={publication.midia}
              empresaId={publication.empresaId}
              curtidas={publication.curtidas}
            />
          ))
        ) : (
          <NotPublics>
            <p>Ainda não tem nada por aqui! :)</p>
            <img src="/em-breve.png" />
          </NotPublics>
        )}
      </Content>
      <SideBar />
    </>
  );
}
