import Head from "next/head";
import { useEffect, useState } from "react";
import { BoxPublic, Header } from "@/components";
import { Content, SideBar } from "@/styles/styles";
import { CompanyInfos } from "@/blocks";
import { IPublication } from "@/components/BoxPublic/BoxPublic";
import { usePosts } from "@/services";

export default function Empresa() {
  const { posts, loading, mutate } = usePosts();
  const [postagensFiltradas, setPostagensFiltradas] = useState([]);

  useEffect(() => {
    if (!posts) return;

    setPostagensFiltradas(
      posts.filter((postagem: any) => postagem.empresaId === 1)
    );
  }, [posts]);

  return (
    <>
      <Head>
        <title>Munera Business</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <SideBar left>
        <CompanyInfos />
      </SideBar>
      <Content>
        {postagensFiltradas?.map((publication: IPublication, key) => (
          <BoxPublic
            key={key}
            empresaName={publication.empresaName}
            icon={`https://munera.s3.sa-east-1.amazonaws.com/logos/${publication.empresaId}-logo.png`}
            date_time={publication.date_time}
            legenda={publication.legenda}
            midia={publication.midia}
            empresaId={publication.empresaId}
            curtidas={publication.curtidas}
          />
        ))}
      </Content>
      <SideBar />
    </>
  );
}
