import Head from "next/head";

import { AddPublic, BoxPublic, Header, Loader } from "@/components";
import { Content, SideBar } from "@/styles/styles";
import { IPublication } from "@/components/BoxPublic/BoxPublic";
import { usePosts } from "@/services";
import { useEffect, useState } from "react";

export default function Home() {
  const { posts, loading, mutate } = usePosts();
  const [idCompany, setIdCompany] = useState<string | null>(null);

  useEffect(() => {
    if (typeof window !== "undefined") {
      setIdCompany(localStorage.getItem("id-company"));
    }
  }, []);

  useEffect(() => {
    const handleReceivedMessage = (event: any) => {
      if (event.data.key === "id-local") {
        setIdCompany(event.data.value);
      }
    };

    if (typeof window !== "undefined") {
      window.addEventListener("message", handleReceivedMessage);
    }

    return () => {
      if (typeof window !== "undefined") {
        window.removeEventListener("message", handleReceivedMessage);
      }
    };
  }, [setIdCompany]);

  return (
    <>
      <Head>
        <title>Munera Business</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/munera-logo.png" />
      </Head>
      <Header />
      <SideBar left />
      <Loader isActive={loading} />
      <Content>
        {idCompany && <AddPublic mutatePublics={mutate} stateMutate={loading}/>}
        {posts?.map((publication: IPublication, key: number) => (
          <BoxPublic
            key={key}
            empresaName={publication.empresaName}
            icon={`${process.env.NEXT_PUBLIC_S3}/logos/${publication.empresaId}-logo.png`}
            date_time={publication.date_time}
            legenda={publication.legenda}
            midia={publication.midia}
            empresaId={publication.empresaId}
            curtidas={publication.curtidas}
          />
        ))}
      </Content>
      <SideBar />
    </>
  );
}
