import Head from "next/head";

import { AddPublic, BoxPublic, Header } from "@/components";
import { Content, SideBar } from "@/styles/styles";
import { IPublication } from "@/components/BoxPublic/BoxPublict";
import { usePosts } from "@/services";

export default function Home() {
  const { posts, loading, mutate } = usePosts();

  return (
    <>
      <Head>
        <title>Munera Business</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <SideBar left />
      <Content>
        <AddPublic mutatePublics={mutate} />
        {posts?.map((publication: IPublication, key: number) => (
          <BoxPublic
            key={key}
            company={"Nome da empresa"}
            icon={"/nu-icon.png"}
            date={publication.date_time}
            content={publication.legenda}
            img={publication.midia}
            codeCompany={publication.codeCompany}
          />
        ))}
      </Content>
      <SideBar />
    </>
  );
}
