import Head from "next/head";
import { BoxPublic, Header } from "@/components";
import { Container } from "@/styles/styles";
import { BoxLeft } from "@/blocks";

export default function Home() {
  return (
    <>
      <Head>
        <title>Teste Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container>
        <BoxLeft />
        <BoxPublic />
      </Container>
    </>
  );
}
