import Head from "next/head";
import { Header } from "@/components";
import { Content, SideBar } from "@/styles/styles";

export default function OfertaPublica() {
  return (
    <>
      <Head>
        <title>Munera Business</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <SideBar left />
      <Content>
        <h1 className="soon">
          Estamos trabalhando para construir essa tela, aguarde.
        </h1>
        <img
          src="/maintenance.png"
          alt="maintenance"
          className="maintenance"
        />
      </Content>
      <SideBar />
    </>
  );
}
